### ISSUE TITLE
[Epic] Resource Refactor

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#152]
The provider is in a healthy place. It would be good to pay down some of the tech debt as right now the code could be much cleaner.

- [x] Move SQL execution into the `materialize` package. Needed to do this for the ownership resource and would be good to standardize this.
- [x] Use `StructScan` for parameter reads.
- [x] Share more generics. Currently All variations of Sinks, Source and Connections implement their own functions for DROP, ALTER... though it is the same for each. Would be good to DRY up.
- [x] Redundant query logic.

Was pushing all these changes into a [single PR](https://github.com/MaterializeInc/terraform-provider-materialize/pull/147) but that was starting to get away from me so break up for the sake of sanity.
