### ISSUE TITLE
[EPIC] Allow `ALTER CONNECTION` Updates

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#368]
[Materialize #21109](https://github.com/MaterializeInc/materialize/pull/21109) will allow `ALTER CONNECTION` for all available options for each connector. All connection resources will need to update their `UpdateContext` to allow for all of the possible updates that can occur.
```[tasklist]
### Tasks
- [ ] https://github.com/MaterializeInc/terraform-provider-materialize/issues/513
- [ ] https://github.com/MaterializeInc/terraform-provider-materialize/issues/514
- [ ] https://github.com/MaterializeInc/terraform-provider-materialize/issues/515
- [ ] https://github.com/MaterializeInc/terraform-provider-materialize/issues/516
- [ ] https://github.com/MaterializeInc/terraform-provider-materialize/issues/517
- [ ] https://github.com/MaterializeInc/terraform-provider-materialize/issues/518
- [ ] https://github.com/MaterializeInc/terraform-provider-materialize/issues/519
```

**Comment by bobbyiliev** [comment]
Closing this one as completed
