### ISSUE TITLE
[EPIC] New MySQL resources

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/terraform-provider-materialize#475]
- [x] Resources:
  - [x] #481
    - [x] Acceptance tests
    - [x] Unit tests
    - [x] Integration tests
  - [x] #482
    - [x] Acceptance tests
    - [x] Unit tests
    - [x] Integration tests

There will be no need for adding a separate data source as the connection data source will work out of the box.
```[tasklist]
### Tasks
- [ ] https://github.com/MaterializeInc/terraform-provider-materialize/issues/420
- [ ] https://github.com/MaterializeInc/terraform-provider-materialize/issues/490
- [ ] https://github.com/MaterializeInc/terraform-provider-materialize/issues/491
- [ ] https://github.com/MaterializeInc/terraform-provider-materialize/issues/519
```

**Comment by bobbyiliev** [comment]
Closing this one as completed for the moment. Will track any additional tasks in separate issues
